version: '3.9' 

volumes:
  mysql_volume:
  wordpress_volume: 

services:
  db:
    container_name: database
    image: mysql:latest
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: pwd123
       MYSQL_DATABASE: wordpress
       MYSQL_USER: user
       MYSQL_PASSWORD: user
    volumes:
      - mysql_volume:/var/lib/mysql

  wordpress:
      container_name: wordpress
      depends_on:
        - db
      image: wordpress:latest
      ports:
        - "8080:80"
      restart: always
      environment:
        WORDPRESS_DB_HOST: db:3306
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_DB_USER: user
        WORDPRESS_DB_PASSWORD: user
      volumes:
        - wordpress_volume:/var/www/html